Vagrant::Config.run do |config|

  config.vm.box = "base"
  config.vm.forward_port 'web',80,4567
  config.vm.provision :chef_solo do |chef|
    # We're going to use a local copy of the cookbooks
    chef.cookbooks_path = "cookbooks"
    # Tell chef what recipe to run. In this case, the `vagrant_main` recipe
    # does all the magic.
    chef.add_recipe("vagrant_main")
  end 
end
